import type { Metadata } from "next";
import { ReduxProvider } from "../redux/provider";
import "./globals.css";
import Navigation from "../components/navigation";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="dark:bg-gray-900 max-w-5xl mx-auto">
				<Navigation />
				<ReduxProvider>{children}</ReduxProvider>
			</body>
		</html>
	);
}
